name: CI/CD Push

on:
  push:
    branches: [ main ]

jobs:
  Deploy:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploying on Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd valorina-ts/
          git reset --hard
          git pull
          rm -rf dist/
          yarn build
          tmux kill-session -t Valorina
          tmux new-session -s Valorina -d "yarn start"